# Generated by Django 6.0.2 on 2026-02-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_num', models.IntegerField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
